### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by aleksandar-todorovic** [nesQuick/atom-wordcount#19]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/opt/atom/resources/app/src/atom.js:54:11)
WordcountView.module.exports.WordcountView.updateWordCountText (/home/r3bl/.atom/packages/wordcount/lib/wordcount-view.coffee:42:18)
```

**Comment by nesQuick** [comment]
Pull requests are very welcome @aleksandar-todorovic

**Comment by claman** [comment]
It looks like the API docs haven't been updated to reflect the deprecation of atom.workspaceView, and I don't currently know enough to try to fix it...

**Comment by aleksandar-todorovic** [comment]
Well I still think that this issue needs to remain open. It _is_ a bug and it _is_ a problem that might break the extension as soon as Atom gets upgraded.

Now knowing how to fix this bug is not an excuse to close the issue.

**Comment by nesQuick** [comment]
The plugin has no deprecated method calls anymore since https://github.com/nesQuick/atom-wordcount/pull/24 so it will remain closed because it is fixed.
