### ISSUE TITLE
[automatic issue] Uncaught TypeError: undefined is not a FUNCTION

### ISSUE THREAD

**Issue by s0r00t** [nesQuick/atom-wordcount#26]
Enter steps to reproduce below:  
1. Open a file 
**Atom Version**: 0.186.0 
**System**: linux 3.13.0-46-generic 
**Thrown From**:  wordcount  https://github.com/nesQuick/atom-wordcount  package, v2.1.0 ### Stack Trace Uncaught TypeError: undefined is not a FUNCTION     At /home/s0/.atom/packages/wordcount/lib/main.coffee:20 TypeError: undefined is not a FUNCTION at /home/s0/.atom/packages/wordcount/lib/main.coffee:20:34 at Emitter.module.exports.Emitter.emit  /usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11  at /usr/share/atom/resources/app/src/text-editor.js:211:32 at Emitter.module.exports.Emitter.emit  /usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11  at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange  /usr/share/atom/resources/app/src/display-buffer.js:318:20  at DisplayBuffer.module.exports.DisplayBuffer.updateWrappedScreenLines  /usr/share/atom/resources/app/src/display-buffer.js:329:19  at DisplayBuffer.module.exports.DisplayBuffer.setWidth  /usr/share/atom/resources/app/src/display-buffer.js:452:14  at TextEditor.module.exports.TextEditor.setWidth  /usr/share/atom/resources/app/src/text-editor.js:2958:33  at TextEditorPresenter.module.exports.TextEditorPresenter.setContentFrameWidth  /usr/share/atom/resources/app/src/text-editor-presenter.js:923:20  at TextEditorComponent.module.exports.TextEditorComponent.measureHeightAndWidth  /usr/share/atom/resources/app/src/text-editor-component.js:832:31  at TextEditorComponent.module.exports.TextEditorComponent.pollDOM  /usr/share/atom/resources/app/src/text-editor-component.js:780:14  at /usr/share/atom/resources/app/src/text-editor-component.js:3:61 at ViewRegistry.module.exports.ViewRegistry.performDocumentPoll  /usr/share/atom/resources/app/src/view-registry.js:186:11  at /usr/share/atom/resources/app/src/view-registry.js:3:61 ### Commands     -8:52.3 settings-view:check-for-package-updates  atom-workspace.workspace.scrollbars-visible-always.theme-cobalt.theme-kobalt-ui.find-visible  -8:52.2 deprecation-cop:view  atom-workspace.workspace.scrollbars-visible-always.theme-cobalt.theme-kobalt-ui.find-visible  -0:50.0 command-palette:toggle  div.settings-view.pane-item  3x -0:47.4 core:backspace  atom-text-editor.editor.mini  -0:46.0 core:select-all  atom-text-editor.editor.mini  -0:44.1 core:CONFIRM  atom-text-editor.editor.mini  -0:44.0 project-find:show  div.settings-view.pane-item  -0:41.4 command-palette:toggle  atom-text-editor.editor.mini  -0:38.1 project-manager:edit-projects  atom-text-editor.editor.mini  -0:17.7 pane:reOPEN-closed-item  ul.list-inline.tab-bar.inset-panel      ### Config    json { core : { themes :   kobalt-ui , cobalt  , projectHome : /home/s0/Dev/ , disabledPackages :   symbols-view   } }     ### Installed Packages    coffee # User atom-jade, v0.1.0 atomatigit, v1.2.3 autocomplete-haxe, v0.2.0 build, v0.25.0 cobalt, v0.3.0 color-picker, v1.4.4 git-diff-details, v0.6.0 git-log, v0.3.0 kobalt-ui, v0.2.1 language-haxe, v0.2.1 language-lua, v0.9.0 language-z80asm, v0.3.0 linter, v0.12.0 minimap, v4.5.0 minimap-git-diff, v4.1.2 project-manager, v1.15.5 script, v2.18.0 travis-ci-status, v0.11.2 tree-view-git-projects, v0.5.0 up2date, v0.0.3 wordcount, v2.1.0 # Dev No dev packages

**Comment by nesQuick** [comment]
I can't reproduce it, and didn;t see a major flaw in the code, so can you debug it further?

**Comment by s0r00t** [comment]
Uhm, wierd. It seems to happen randomly. I'll try to debug it further.

**Comment by nesQuick** [comment]
Thank you very much!

**Comment by k2052** [comment]
I had the same issue. I couldn't determine the cause but the quick fix was to just add an if to check if the view is not null

```coffeescript
atom.workspace.observeTextEditors (editor) ->
  editor.onDidChange -> view.update_count(editor) if view
  editor.onDidChangeSelectionRange -> view.update_count(editor) if view
```

**Comment by nesQuick** [comment]
I assume it's not the view which is not defined, because it is always
defined here:
https://github.com/nesQuick/atom-wordcount/blob/master/lib/main.coffee#L17
where I have no idea if editor might be undef sometimes

**Comment by nesQuick** [comment]
I did not receive any more reports on this, also no way to reproduce this. If anyone has a way to reproduce this with the current versions of atom and the word count plugin please reopen this issue.
