### ISSUE TITLE
Add "Enable for all files" setting

### ISSUE THREAD

**Issue by jeffmcneill** [nesQuick/atom-wordcount#35]
Not sure the issue, how can I troubleshoot?

**Comment by jeffmcneill** [comment]
Never mind, I had to add the file extension for the files I was working on. Perhaps there could be a setting to "enable for all" or for only some by extension?

**Comment by skycaptain** [comment]
+1. I often copy-paste a text-sample to atom to count the words. By default a unsaved file is set in plain text mode. It would be great if wordcount could be enabled by default on new unsaved files as well.

**Comment by jeffmcneill** [comment]
+1 on default, non-saved files as well. I have the same use case as @skycaptain

**Comment by nesQuick** [comment]
sure, valid feature request, I just adjusted the "error". also PR's welcome ;)
