### ISSUE TITLE
Optionally don't count code blocks in md

### ISSUE THREAD

**Issue by bsparks** [nesQuick/atom-wordcount#41]
It would be nice to ignore all of my code blocks in markdown. The source code examples in a blog post shouldn't count as words IMO.

**Comment by nesQuick** [comment]
I think this sounds like a great addition to wordcount, would love to see a PR :sparkles:

**Comment by smaxtastic** [comment]
I was craving for that option, too :) I filed a PR here: https://github.com/nesQuick/atom-wordcount/pull/43.

It includes an extra option in the plugin settings and covers both normal markdown and Github-flavored markdown.

@bsparks Any opinion on inline code? Should that maybe count as one word or is the default way sufficient?

**Comment by nesQuick** [comment]
@smaxtastic that's awesome, thanks a bunch for your contribution! :sparkling_heart:

**Comment by nesQuick** [comment]
fixed with #43
