### ISSUE TITLE
Activate plugin for unsaved buffers

### ISSUE THREAD

**Issue by cle1109** [nesQuick/atom-wordcount#42]
It would be great if the plugin could be activated for unsaved buffers - that way, users can quickly count words from text inserted e.g. from the clipboard.

**Comment by nesQuick** [comment]
That sounds like a great addition, PR welcome :)

**Comment by nesQuick** [comment]
Huge thanks to @smaxtastic for adding it, I'm going to bump a new version asap :+1:

**Comment by cle1109** [comment]
Awesome, thanks @smaxtastic!
