### ISSUE TITLE
Hangs atom worker on triple backtick above long paragraph

### ISSUE THREAD

**Issue by vsivsi** [nesQuick/atom-wordcount#50]
Hi, this seems like a great package, but I just installed and started using it while editing a large markdown project and suddenly started getting weird hangs whenever I type triple backticks to start a fenced codeblock. I immediately suspected this package because I had only just started using it when the hangs started happening, but I have since spent the past hour really narrowing it down and I'm convinced it's just wordcount.  I've tried disabling all community packages, and then everything is fine.  If I then enable *just* wordcount, the hang starts happening.  If I enable all community packages *except* workdcount, everything is fine. Enable wordcount?  Hangs.

Here's my repo:  Lauch Atom fresh with wordcount previously enabled.

1.  Paste in a long paragraph of text (no line breaks), like some sweet sweet hipster ipsum:

```
Fanny pack shabby chic tacos whatever craft beer, lo-fi actually bushwick. Chia poutine biodiesel flannel, banh mi cornhole hoodie taxidermy listicle +1 disrupt. Listicle franzen tattooed, banjo everyday carry migas butcher bitters artisan readymade thundercats food truck yuccie. Mixtape lomo fashion axe, vinyl disrupt asymmetrical authentic chia sustainable letterpress pug pinterest tofu meh schlitz. Selfies bushwick meh williamsburg tote bag ethical mustache, pop-up roof party portland chia kinfolk. 3 wolf moon bushwick kinfolk, lo-fi vice venmo asymmetrical VHS. Cronut cold-pressed chillwave swag.
```

2.  Type: [command] [up-arrow] to go to the beginning of document.
3.  Hit return twice (insert two blank lines).
4.  Hit up-arrow twice (back to top of document)
5.  Hit \` (backtick)  You will get two due to autocomplete.
6.  Hit \` (backtick) again (overwrites the second one from above)
7.  Hit \` (backtick) again.
8.  Profit.  Actually no, hang until the "Editor is not responding" modal popups up, then either wait forever, or click close to lose all your work since the last save.  I screenshot a whole page of text the first time this happened, so thankfully I just needed to type it in again...

I have no idea why this is happening, but needless to say, I need to disable wordcount until something changes!

**Comment by vsivsi** [comment]
Because I'm a glutton for punishment, I just verified that it is something special about backticks. Doing it with single or double quotes (which have the same autocomplete behavior) has no effect. And it's not a markdown language specific issue, because the same happens if the document is "plain text".

**Comment by vsivsi** [comment]
Disabling the `Ignore Markdown code blocks` option makes the issue go away, so I'm guessing the problem is here: https://github.com/nesQuick/atom-wordcount/blob/master/lib/wordcount-view.coffee#L43-L46

I've written a lot of Coffeescript (not for Atom), but just starting at those 4 lines at midnight, I can't trivially see how that `for` loop or `replace` can go infinite, which seems to be what's happening...  Hmm

**Comment by vsivsi** [comment]
Well, I just had my first Atom debugging session and what is happening is that as soon as there are three opening backticks without three closing backticks, the `replace` at [line 46](https://github.com/nesQuick/atom-wordcount/blob/master/lib/wordcount-view.coffee#L46) crashes in a bad way.  Looks like as soon as the initial clause of that regex is satisfied, the `replace` scans to the end of the `text` string looking for the closing backticks and when it gets to the end, bad things happen. It literally blows right out of the debugger.  The same code works fine the the coffeescript REPL, so this must be an Atom quirk.  I dunno.

**Comment by vsivsi** [comment]
Seems like a case of [catastrophic backtracking](https://stackoverflow.com/questions/13562435/infinite-loop-with-regex)...  

Modifying the triple backtick replace regex to add an end of string condition solves it.

```
/`{3}(.|\s)*?(`{3}|$)/g
```

Procrastination achievement unlocked!

**Comment by nesQuick** [comment]
@vsivsi I was reading your monologue that Sunday and love how you dug into the issue. I really want to thank you for finding, reporting and especially fixing it! <3 I'm going to get this in and release a new version asap :)

**Comment by vsivsi** [comment]
Awesome, thanks!  I'm writing my Ph.D. Dissertation with Atom in Pandoc flavored Markdown. This was an excuse to work on something else (and learn how Atom packages work) before bed on Sunday.

**Comment by nesQuick** [comment]
Awesome! So nice to hear that people use this midnight hack for such important things like a Ph.D. good luck with that! Just take a look at the issues if you need more breaks :grinning:
