### ISSUE TITLE
Use onDidStopChanging to reduce resource consumption

### ISSUE THREAD

**Issue by mangecoeur** [nesQuick/atom-wordcount#52]
I use Atom as my writing editor, so I end up with some pretty long markdown files. I find that wordcount eats up CPU since it re-counts the whole document on every keystroke - when you are typing fast and the document is long I found this causes a spike in CPU usage.

Using onDidStopChanging instead of onChange would help a lot, since it would prevent the wordcount re-running as often.

Another alternative would be to add an option option to only do the wordcount on save

**Comment by nesQuick** [comment]
Constant recalculation should be solved with a `debounce` like the lodash version for example: https://lodash.com/docs#debounce

PRs welcome <3

**Comment by mangecoeur** [comment]
Wouldn't that basically do the same thing as onDidStopChanging ? That function also just waits until 330milliseconds after the last keystroke before invoking, my first instinct is that the result would be the same as using debounce?

**Comment by nesQuick** [comment]
Well in the default configuration it would basically be the same, I just want to be sure the func will be executed which could be done with the `maxWait` parameter. As described in their docs:

> [options.maxWait] (number): The maximum time func is allowed to be delayed before it’s invoked.

**Comment by nesQuick** [comment]
A little update on that: I meant actually `throttle` https://lodash.com/docs#throttle
