### ISSUE TITLE
Option to only show word count (no character count)

### ISSUE THREAD

**Issue by mangecoeur** [nesQuick/atom-wordcount#61]
The character count IMHO is not terribly informative, it would be nice to have an option to only show word count and reduce status bar clutter a little

**Comment by nesQuick** [comment]
Due to the fact that the plugin is highly configurable anyway, I do like
the idea of having the option. But the default should be showing it, so we
don't introduce a BC here.

I'd like to see a PR for that :+1:

**Comment by nesQuick** [comment]
Fixed by #68
