### ISSUE TITLE
Count words in multiple selections

### ISSUE THREAD

**Issue by villermen** [nesQuick/atom-wordcount#72]
Right now only the last selection is used for word count. I want to be able to select relevant parts of the text (e.g. in LaTeX documents with a lot of command sections and code sections) and have them tallied together.

![word count](https://cloud.githubusercontent.com/assets/1106303/20880568/16f73590-bad9-11e6-9e87-adc06a92d160.png)

Please tell me if this is a wanted addition, and I'll get you a PR.

**Comment by nesQuick** [comment]
Hey @villermen I was not aware of that. And this is totally a addiction I'd love to see.

Looking forward to a PR 👍 Let me know if you need help.

**Comment by nesQuick** [comment]
I just published `2.10.0` containing your changes. Again, thank you very much ✨
