### ISSUE TITLE
Words are counted even when the result is not viewed

### ISSUE THREAD

**Issue by villermen** [nesQuick/atom-wordcount#73]
A thing I came across trying to implement #72.

**Comment by nesQuick** [comment]
Could you elaborate on this a bit? Or if you feel it's a easy one, send over a PR?

thanks!

**Comment by villermen** [comment]
I added a debug log statement somewhere in `WordcountView::getCurrentText` and noticed it was fired even in the .coffee file I was editing. So the count is probably being calculated even for files that are excluded by the configuration.

**Comment by nesQuick** [comment]
Yes, you are right. Let's continue this in the PR 👍

**Comment by nesQuick** [comment]
I just published `2.10.0` containing your changes. Again, thank you very much ✨
