### ISSUE TITLE
No Goal indicator visible

### ISSUE THREAD

**Issue by rudygasson** [nesQuick/atom-wordcount#80]
I could not find any example of how the goal indicator or bar should look like, but if I set a goal and a color I cannot see anything that is drawn or changes while writing towards the goal and reach it. Any hints or ideas?

Example: Set goal to 130 words, color: default

![bildschirmfoto 2017-01-08 um 11 53 27](https://cloud.githubusercontent.com/assets/2715405/21749190/f24f2fbe-d599-11e6-99bf-e995f8dadf5a.png)
![bildschirmfoto 2017-01-08 um 11 53 49](https://cloud.githubusercontent.com/assets/2715405/21749191/f253204c-d599-11e6-945f-240108bc8fe6.png)
![bildschirmfoto 2017-01-08 um 11 56 40](https://cloud.githubusercontent.com/assets/2715405/21749192/f256f55a-d599-11e6-9575-a00892db117a.png)

**Comment by nesQuick** [comment]
Thanks for the report @rudygasson I can reproduce it. Yet I did not have any time to look into it. PR's are definitely welcome ✨

**Comment by nesQuick** [comment]
this fix is included in `2.10.3`
